Script started on 2017年03月10日 (週五) 11時12分05秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami; pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -l
user.email=wyyaclqyr@hotmail.com
user.name=gudstudent
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m fi=[K[K[Kgit clone https://github.com/gudstudent/lab1
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m exit

Script done on 2017年03月10日 (週五) 11時13分00秒
